site_name: awesome-social-agents

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
      - header.autohide
      - navigation.tabs
      - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  version:
    default: latest
    provider: mike
  generator: false

repo_name:  awesome-social-agents
repo_url: https://github.com/sotopia-lab/awesome-social-agents

markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - admonition
  - pymdownx.details
  - mkdocs-click

plugins:
  - mike:
      version_selector: true
      canonical_version: null
      css_dir: css
      javascript_dir: js
  - search:
  - callouts